#!/bin/bash

set -e
set -x

cp bash_aliases ~/.bash_aliases
cp gitconfig ~/.gitconfig

mkdir -p ~/bin/
export PATH=~/bin:$PATH

# GH CLI
VERSION=2.24.3
if [[ ! -d "~/apps/gh/${VERSION}" ]]; then
  wget https://github.com/cli/cli/releases/download/v${VERSION}/gh_${VERSION}_linux_amd64.tar.gz -O gh.tar.gz
  rm -f ~/apps/gh/latest
  rm -rf ~/apps/gh/${VERSION}
  mkdir -p ~/apps/gh/${VERSION}
  tar -C ~/apps/gh/${VERSION} -x -v --strip-components=1 -f gh.tar.gz
  ln -sf  ~/apps/gh/${VERSION}/ ~/apps/gh/latest
  ln -sf ~/apps/gh/latest/bin/gh ~/bin/gh
  rm gh.tar.gz
fi

# Go
VERSION=1.20.2
if [[ ! -d "~/apps/go/${VERSION}" ]]; then
  wget https://go.dev/dl/go${VERSION}.linux-amd64.tar.gz -O go.tar.gz
  rm -rf ~/apps/go/latest
  rm -rf ~/apps/go/${VERSION}
  mkdir -p ~/apps/go/${VERSION}
  tar -C ~/apps/go/${VERSION} -x -v -f go.tar.gz
  ln -sf  ~/apps/go/${VERSION}/ ~/apps/go/latest
  ln -sf ~/apps/go/latest/go/bin/go ~/bin/go
  rm go.tar.gz
fi

# Helm
VERSION=3.11.2
if [[ ! -d "~/apps/helm/${VERSION}" ]]; then
  wget https://get.helm.sh/helm-v${VERSION}-linux-amd64.tar.gz -O helm.tar.gz
  rm -rf ~/apps/helm/latest
  rm -rf ~/apps/helm/${VERSION}
  mkdir -p ~/apps/helm/${VERSION}
  tar -C ~/apps/helm/${VERSION} -x -v --strip-components=1 -f helm.tar.gz
  ln -sf  ~/apps/helm/${VERSION}/ ~/apps/helm/latest
  ln -sf ~/apps/helm/latest/helm ~/bin/helm
  rm helm.tar.gz
fi


# kOps
VERSION=1.26.2
if [[ ! -d "~/apps/kops/${VERSION}" ]]; then
  rm -rf ~/apps/kops/latest
  rm -rf ~/apps/kops/${VERSION}
  mkdir -p ~/apps/kops/${VERSION}
  wget https://github.com/kubernetes/kops/releases/download/v${VERSION}/kops-linux-amd64 -O ~/apps/kops/${VERSION}/kops
  chmod +x ~/apps/kops/${VERSION}/kops
  ln -sf  ~/apps/kops/${VERSION}/ ~/apps/kops/latest
  ln -sf ~/apps/kops/latest/kops ~/bin/kops
fi

# kubectl
VERSION=1.26.2
if [[ ! -d "~/apps/kubectl/${VERSION}" ]]; then
  rm -rf ~/apps/kubectl/latest
  rm -rf ~/apps/kubectl/${VERSION}
  mkdir -p ~/apps/kubectl/${VERSION}
  wget https://dl.k8s.io/release/v${VERSION}/bin/linux/amd64/kubectl -O ~/apps/kubectl/${VERSION}/kubectl
  chmod +x ~/apps/kubectl/${VERSION}/kubectl
  ln -sf  ~/apps/kubectl/${VERSION}/ ~/apps/kubectl/latest
  ln -sf ~/apps/kubectl/latest/kubectl ~/bin/kubectl
fi

./install-srctool