#!/bin/bash

set -e
set -x

dconf dump /org/gnome/desktop/wm/keybindings/ > org.gnome.desktop.wm.keybindings
dconf dump /org/gnome/desktop/interface/ > org.gnome.desktop.interface
dconf dump /org/gnome/mutter/keybindings/ > org.gnome.mutter.keybindings

