#!/bin/bash

set -e
set -x

ARCH=$(uname -m)
OS=$(uname -s)

if [[ "${OS}" == "Linux" ]]; then
  OS=linux
elif [[ "${OS}" == "Darwin" ]]; then
  OS=darwin
fi

if [[ "${ARCH}" == "x86_64" ]]; then
  ARCH=amd64
fi

BIN=~/.local/bin
mkdir -p ${BIN}

APPS=~/.local/apps
mkdir -p ${APPS}

download_file() {
  # Usage: download_file <url> <output_file>
  local url="$1"
  local output="$2"
  curl -L --fail "$url" -o "$output"
}

# kOps
kops_versions=( "1.26.2" )
for VERSION in "${kops_versions[@]}"; do
  if [[ ! -d "${APPS}/kops/${VERSION}" ]]; then
    #rm -rf ${APPS}/kops/latest
    rm -rf ${APPS}/kops/${VERSION}
    mkdir -p ${APPS}/kops/${VERSION}
    download_file https://github.com/kubernetes/kops/releases/download/v${VERSION}/kops-${OS}-${ARCH} ${APPS}/kops/${VERSION}/kops
    chmod +x ${APPS}/kops/${VERSION}/kops
    #ln -sf  ${APPS}/kops/${VERSION}/ ${APPS}/kops/latest
    ln -sf ${APPS}/kops/${VERSION}/kops ${BIN}/kops-${VERSION}
  fi
done
