#!/bin/bash

set -e
set -x

ARCH=$(uname -m)
OS=$(uname -s)

if [[ "${OS}" == "Linux" ]]; then
  OS=linux
elif [[ "${OS}" == "Darwin" ]]; then
  OS=darwin
fi

if [[ "${ARCH}" == "x86_64" ]]; then
  ARCH=amd64
fi

BIN=~/.local/bin
mkdir -p ${BIN}

APPS=~/.local/apps
mkdir -p ${APPS}

download_file() {
  # Usage: download_file <url> <output_file>
  local url="$1"
  local output="$2"
  curl -L --fail "$url" -o "$output"
}

# Terraform
VERSION=1.5.6
if [[ ! -d "${APPS}/terraform/${VERSION}" ]]; then
  rm -rf ${APPS}/terraform/latest
  rm -rf ${APPS}/terraform/${VERSION}
  mkdir -p ${APPS}/terraform/${VERSION}
  pushd ${APPS}/terraform/${VERSION}
  download_file "https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_${OS}_${ARCH}.zip" "terraform.zip"
  unzip terraform.zip
  rm terraform.zip
  popd
  ln -sf  ${APPS}/terraform/${VERSION}/ ${APPS}/terraform/latest
  ln -sf ${APPS}/terraform/latest/terraform ${BIN}/terraform
fi
