#!/bin/bash -ex

mkdir -p ~/bin

ln -s -f /usr/bin/google-chrome ~/bin/chrome
mkdir -p ~/apps

#if [[ ! -e ~/apps/eclipse ]]; then
#	wget "http://ftp.osuosl.org/pub/eclipse//technology/epp/downloads/release/kepler/SR2/eclipse-java-kepler-SR2-linux-gtk-x86_64.tar.gz" -O /tmp/eclipse.tar.gz
#
#	cd ~/apps/
#	tar zxf /tmp/eclipse.tar.gz
#fi
#
#ln -s -f ~/apps/eclipse/eclipse ~/bin/eclipse

if [[ ! -e ~/apps/webstorm ]]; then
	wget "http://download.jetbrains.com/webstorm/WebStorm-9.0.3.tar.gz" -O /tmp/webstorm.tar.gz
	cd ~/apps
	tar zxf /tmp/webstorm.tar.gz
	ln -s WebStorm-139.1112 webstorm
        rm /tmp/webstorm.tar.gz
fi

ln -s -f ~/apps/webstorm/bin/webstorm.sh ~/bin/webstorm


