#!/bin/bash -ex

if [[ ! -e /etc/apt/sources.list.d/google.list ]] ; then
	echo "deb http://dl.google.com/linux/deb/ stable main" > /etc/apt/sources.list.d/google.list

	wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

fi

apt-get update

apt-get install --yes sudo
apt-get install --yes google-chrome-stable
apt-get install --yes gedit
apt-get install --yes git bzr mercurial
apt-get install --yes awesome awesome-extra
apt-get install --yes openjdk-7-jdk
apt-get install --yes htop iftop
apt-get install --yes vim
apt-get install --yes pip

apt-get install --yes screen
apt-get install --yes gdm3 || apt-get install --yes gdm
apt-get install --yes gnome-terminal fonts-noto fonts-liberation
apt-get install --yes x11-apps

if [[ ! -e /usr/local/go ]]; then
	wget "https://storage.googleapis.com/golang/go1.4.1.linux-amd64.tar.gz" -O /tmp/go.tar.gz
	tar -C /usr/local -xzf /tmp/go.tar.gz
fi


