#!/bin/bash -ex


echo "deb http://dl.google.com/linux/deb/ stable main" > /etc/apt/sources.list.d/google.list

wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -


apt-get update

apt-get install --yes google-chrome-stable

