#!/bin/bash

apt-get --yes install gcc make linux-headers-$(uname -r)

mkdir -p /opt/vmware
mnt /dev/cdrom /media/cdrom
cp -r /media/cdrom/* /opt/vmware

/opt/vmware/run_upgrader.sh

You must restart your X session before any mouse or graphics changes take 
effect.

You can now run VMware Tools by invoking "/usr/bin/vmware-toolbox-cmd" from the
command line.

To enable advanced X features (e.g., guest resolution fit, drag and drop, and 
file and text copy/paste), you will need to do one (or more) of the following:
1. Manually start /usr/bin/vmware-user
2. Log out and log back into your desktop session; and,
3. Restart your X session.

